export const GET_PROFILE = "GET_PROFILE"
export const GET_HANDLE_PROFILE = "GET_HANDLE_PROFILE"
export const GET_EDUCATION = "GET_EDUCATION"
export const ADD_EDUCATION = "ADD_EDUCATION"
export const DELETE_EDUCATION = "DELETE_EDUCATION"





